export const SET_SEARCH = 'SET_SEARCH'
export const FETCH_STARSHIPS = 'FETCH_STARSHIPS'
export const FETCH_SHARSHIPS_FULFILLED = 'FETCH_SHARSHIPS_FULFILLED'
export const FETCH_STARSHIPS_REJECTED = 'FETCH_STARSHIPS_REJECTED'
